# Generated by Django 2.2.16 on 2022-05-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                error_messages={
                    'unique': 'A user with that email already exists.'
                },
                max_length=254,
                unique=True,
                verbose_name='Email',
            ),
        ),
    ]
