# Generated by Django 2.2.16 on 2022-05-23 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220523_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={},
        ),
    ]
