# Generated by Django 2.2.16 on 2022-05-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220524_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.TextField(),
        ),
    ]
